### ISSUE TITLE
How is this thing supposed to work?

### ISSUE THREAD

**Issue by josefsabl** [Thavarshan/matrix#1]
- Library Version: 1.0.1
- PHP Version:  8.3.0

### Description

The asynchronicity is not working. I also don't understand how you used fibers for asynchronicity.

### Steps To Reproduce

I assumed that something like this:

```php
        async(
            function() {
                echo '1';
                usleep(500000); // 500ms delay
                echo '1';
                usleep(500000); // 500ms delay
                echo '1';
                usleep(500000); // 500ms delay
                return 'Finished 1';
            }
        )
            ->then(function(string $result) {
                echo $result;
            });

        async(
            function() {
                echo '2';
                usleep(500000); // 500ms delay
                echo '2';
                usleep(500000); // 500ms delay
                echo '2';
                usleep(500000); // 500ms delay
                return 'Finished 2';
            }
        )
            ->then(function(string $result) {
                echo $result;
            });
```

will print

```
1
2
1
2
1
2
Finished 1
Finished 2
```

but it prints

```
1
1
1
Finished 1
2
2
2
Finished 2
```

**Comment by Thavarshan** [comment]
Thanks for opening this issue and providing a clear example. You raise an important point about the core functionality of Matrix.

The current implementation isn't delivering on our goal of providing a simple, JavaScript-like async API that "just works." Adding a scheduler or requiring additional wrappers would go against the project's goal of keeping things simple and intuitive.

I'd like to refactor the implementation to achieve the behavior you expected. Your example perfectly illustrates how the API should work:

```php
async(function() {
    echo '1';
    usleep(500000);
    echo '1';
    usleep(500000);
    echo '1';
    usleep(500000);
    return 'Finished 1';
})->then(/* ... */);

async(function() {
    echo '2';
    usleep(500000);
    // ...
})->then(/* ... */);
```

This should naturally produce interleaved output like:
```
1
2
1
2
1
2
Finished 1
Finished 2
```

Would you be interested in collaborating on this refactor to make the API work as intuitively as shown in your example?

**Comment by ejunker** [comment]
Here is how they handle it in `amphp/parallel`. Maybe a similar syntax would work for Matrix.

```php
<?php

require 'vendor/autoload.php';

use Amp\Future;

use function Amp\async;
use function Amp\delay;

// composer require amphp/parallel

$tasks = [];

for ($i = 1; $i <= 2; $i++) {
    $tasks[] = async(function () {
        delay(1);

        return 'Result 1';
    });
    $tasks[] = async(function () {
        delay(1);

        return 'Result 2';
    });
}

// Wait for all tasks to complete and collect results
$results = Future\await($tasks);

foreach ($results as $index => $result) {
    echo "Task $index completed: $result\n";
}

```

**Comment by josefsabl** [comment]
I'm afraid the goal can't be achieved using only fibers. Fibers don't provide asynchronous functionality. While they do allow the creation of separate "threads" (or "fibers"), it doesn’t mean that both can run in parallel. One fiber runs while the other is paused, and they must switch between each other somehow (using Fiber::suspend).

Please see this thread: https://www.reddit.com/r/PHP/comments/t8ubvp/i_dont_get_the_point_of_fibers_or_how_they_make/

As I understand it, you can't add parallelism to something that doesn't inherently support it simply by introducing fibers. For example, consider sleep versus Guzzle async requests. While two Guzzle async requests can run in parallel, two sleep operations cannot.

**Comment by josefsabl** [comment]
> Here is how they handle it in `amphp/parallel`

You removed this from their example :-)

```
// delay() is a non-blocking version of PHP's sleep() function,
// which only pauses the current fiber instead of blocking the whole process.
```

This is very important and is the point. You cannot make PHP's built in `sleep` function non-blocking by using fibers (or any other way).

The AMP's `delay` function (https://github.com/amphp/amp/blob/138801fb68cfc9c329da8a7b39d01ce7291ee4b0/src/functions.php#L63) uses `Revolt\EventLoop::delay` function (https://github.com/revoltphp/event-loop/blob/358572ca31647df7dbe930f13c8567136beffa33/src/EventLoop.php#L121) which itself uses `Revolt\EventLoop\Driver::delay` function (https://github.com/revoltphp/event-loop/blob/358572ca31647df7dbe930f13c8567136beffa33/src/EventLoop/Driver.php#L97).

The `Revolt\EventLoop\Driver` is only an interface though. So you have to have some implementation of the driver. There are some built in Drivers, but they all depend on PHP Extensions:

- https://www.php.net/manual/en/class.eventbase.php
- https://www.php.net/manual/en/class.splqueue.php
- https://www.php.net/manual/en/class.evloop.php
- https://docs.libuv.org/en/v1.x/migration_010_100.html

So no, I believe you cannot achieve true parallelism in vanilla PHP (without extensions).

Yeah, it makes me sad too :-)

**Comment by Thavarshan** [comment]
Well then, we'll just have to make do with extensions I suppose. I plan on integrating `pcint_fork` in a future release.

**Comment by josefsabl** [comment]
Maybe you should implement more solutions like AMP (by something like "driver"). Maybe someone will already have one of the existing extensions and would like to use your library.

You may as well only include only `pcint_fork` as you planned and let others implement drivers for different libraries. But let users use their existing solution.

**Comment by Thavarshan** [comment]
Hi @josefsabl 

I finally got time to work on Matrix and may have finally acheived the goal of this package. I've even written integration test that follow your initial example and it producess the expected result. 

Would love to know what you think?

**Comment by ejunker** [comment]
@Thavarshan maybe you are aware of this but `pcntl_fork` is generally not advised to use within web requests. So, a limitation would be that this would only be good for command line PHP code.

**Comment by Thavarshan** [comment]
Thanks for pointing that out @ejunker 

I might refactor it to just rely on ReactPHP then and just avoid using ’pcntl_fork’

**Comment by ejunker** [comment]
@Thavarshan I think you are running into PHP's limitations for how to do asynchronous programming. You can use ReactPHP but then you need an event loop and special versions of libraries that are compatible with the event loop. For example, if you want to do a database query you would need to use a special async mysql client like https://github.com/friends-of-reactphp/mysql

**Comment by Thavarshan** [comment]
God damn it! 🤦‍♂️

**Comment by ejunker** [comment]
For reference, see this library that the ReactPHP team created: https://reactphp.org/async/

> React/Async will not automagically change blocking code to be async. You need to have an actual event loop and non-blocking libraries interacting with that event loop for it to work. As long as you have a Promise-based API that runs in an event loop, it can be used with this library.

**Comment by Thavarshan** [comment]
For my own sanity I think I'll just leave it as it is. It's documented enough so people can use it the way they want to.

Maybe I'll work on it if someone reports a major issue with it.
